# This compose file is useful for testing https.
# The .env file sets ENVVARS for the Docker CLI used by this compose file.
---
version: "3"
services:
  beulah:
    build: .
    # image: beulah-images
    ports:
      - 8050:8050
    container_name: beulah-images
    command: [ "gunicorn", "-b", ":8050", "app:server" ]
